// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Project

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Loadding
void ui_Loadding_screen_init(void);
extern lv_obj_t * ui_Loadding;
extern lv_obj_t * ui_Loadding_Title;
extern lv_obj_t * ui_Loadding_LoadContainer;
extern lv_obj_t * ui_Loadding_LoadText;
extern lv_obj_t * ui_Loadding_LoadPercent;
extern lv_obj_t * ui_Loadding_LoadBar;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Main_MainTabView;
extern lv_obj_t * ui_Main_Dashboard;
extern lv_obj_t * ui_Main_DashPanel;
void ui_event_Main_ZoomBtn(lv_event_t * e);
extern lv_obj_t * ui_Main_ZoomBtn;
extern lv_obj_t * ui_Main_Label9;
void ui_event_Main_HistoryBtn(lv_event_t * e);
extern lv_obj_t * ui_Main_HistoryBtn;
extern lv_obj_t * ui_Main_Label13;
extern lv_obj_t * ui_Main_VolumeArc;
extern lv_obj_t * ui_Main_StatusLabel;
extern lv_obj_t * ui_Main_VolumeLabel;
extern lv_obj_t * ui_Main_UnitLabel;
extern lv_obj_t * ui_Main_ProgressLabel;
extern lv_obj_t * ui_Main_TakeTLabel;
extern lv_obj_t * ui_Main_TimeLabel;
extern lv_obj_t * ui_Main_DetailLabel;
extern lv_obj_t * ui_Main_Setting;
extern lv_obj_t * ui_Main_SettingPanel;
extern lv_obj_t * ui_Main_RightContainer;
extern lv_obj_t * ui_Main_VolContainer;
extern lv_obj_t * ui_Main_SVLabel;
extern lv_obj_t * ui_Main_SVSpinbox;
extern lv_obj_t * ui_Main_SVUnit;
extern lv_obj_t * ui_Main_FlowContainer;
extern lv_obj_t * ui_Main_SFLabel;
extern lv_obj_t * ui_Main_SFSpinbox;
extern lv_obj_t * ui_Main_SFUnit;
extern lv_obj_t * ui_Main_AlarmContainer;
extern lv_obj_t * ui_Main_WALabel;
void ui_event_Main_WASwitch(lv_event_t * e);
extern lv_obj_t * ui_Main_WASwitch;
extern lv_obj_t * ui_Main_LeftContainer;
extern lv_obj_t * ui_Main_Container2;
extern lv_obj_t * ui_Main_Label8;
void ui_event_Main_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Main_Slider1;
extern lv_obj_t * ui_Main_SystemContainer;
void ui_event_Main_ResetBtn(lv_event_t * e);
extern lv_obj_t * ui_Main_ResetBtn;
extern lv_obj_t * ui_Main_ResetLabel;
void ui_event_Main_RebootBtn(lv_event_t * e);
extern lv_obj_t * ui_Main_RebootBtn;
extern lv_obj_t * ui_Main_RebootLabel;
extern lv_obj_t * ui_Main_Info;
extern lv_obj_t * ui_Main_InfoPanel;
extern lv_obj_t * ui_Main_InfoText;
extern bool ESPRestart;
extern bool ResetConf;
extern bool WAStatus;
extern int Poffset;
// SCREEN: ui_DashboardFull
void ui_DashboardFull_screen_init(void);
extern lv_obj_t * ui_DashboardFull;
extern lv_obj_t * ui_DashboardFull_VolumeArc;
extern lv_obj_t * ui_DashboardFull_StatusLabel;
extern lv_obj_t * ui_DashboardFull_VolumeLabel;
extern lv_obj_t * ui_DashboardFull_UnitLabel;
extern lv_obj_t * ui_DashboardFull_ProgressLabel;
extern lv_obj_t * ui_DashboardFull_TakeTLabel;
extern lv_obj_t * ui_DashboardFull_TimeLabel;
void ui_event_DashboardFull_BackBtn(lv_event_t * e);
extern lv_obj_t * ui_DashboardFull_BackBtn;
extern lv_obj_t * ui_DashboardFull_BackLabel;
// SCREEN: ui_History
void ui_History_screen_init(void);
extern lv_obj_t * ui_History;
extern lv_obj_t * ui_History_HisPanel;
void ui_event_History_BackBtn(lv_event_t * e);
extern lv_obj_t * ui_History_BackBtn;
extern lv_obj_t * ui_History_BackLabel;
extern lv_obj_t * ui_History_Title;
extern lv_obj_t * ui_History_HisTitle;
extern lv_obj_t * ui_History_HisData;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_btec_png);    // assets/btec.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
