// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Project

#include "ui.h"
#include <Arduino.h>
bool ESPRestart = false;
bool ResetConf = false;
bool WAStatus = true;
void WAEvent(lv_event_t * e)
{
  WAStatus = !WAStatus;
}

void ResetSystem(lv_event_t * e)
{
  ResetConf = true;
}

void RebootSystem(lv_event_t * e)
{
  ESPRestart = true;
}
