// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Project

#include "ui.h"

void ui_Loadding_screen_init(void)
{
    ui_Loadding = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Loadding, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Loadding, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Loadding, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Loadding, lv_color_hex(0x161616), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loadding, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Loadding, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Loadding, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Loadding, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Loadding, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loadding_Title = lv_label_create(ui_Loadding);
    lv_obj_set_width(ui_Loadding_Title, lv_pct(100));
    lv_obj_set_height(ui_Loadding_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Loadding_Title, 0);
    lv_obj_set_y(ui_Loadding_Title, -20);
    lv_obj_set_align(ui_Loadding_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loadding_Title, "Liquid Filling Machine V 1");
    lv_obj_add_flag(ui_Loadding_Title, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Loadding_Title, lv_color_hex(0x379CF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loadding_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Loadding_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Loadding_Title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loadding_LoadContainer = lv_obj_create(ui_Loadding);
    lv_obj_remove_style_all(ui_Loadding_LoadContainer);
    lv_obj_set_height(ui_Loadding_LoadContainer, 41);
    lv_obj_set_width(ui_Loadding_LoadContainer, lv_pct(100));
    lv_obj_set_x(ui_Loadding_LoadContainer, -118);
    lv_obj_set_y(ui_Loadding_LoadContainer, 2);
    lv_obj_set_align(ui_Loadding_LoadContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Loadding_LoadContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Loadding_LoadContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Loadding_LoadContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Loadding_LoadText = lv_label_create(ui_Loadding_LoadContainer);
    lv_obj_set_width(ui_Loadding_LoadText, lv_pct(50));
    lv_obj_set_height(ui_Loadding_LoadText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Loadding_LoadText, -197);
    lv_obj_set_y(ui_Loadding_LoadText, 85);
    lv_obj_set_align(ui_Loadding_LoadText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loadding_LoadText, "Setup Configulation System");
    lv_obj_set_style_text_color(ui_Loadding_LoadText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loadding_LoadText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Loadding_LoadText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loadding_LoadPercent = lv_label_create(ui_Loadding_LoadContainer);
    lv_obj_set_width(ui_Loadding_LoadPercent, lv_pct(50));
    lv_obj_set_height(ui_Loadding_LoadPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Loadding_LoadPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loadding_LoadPercent, "0 %");
    lv_obj_set_style_text_color(ui_Loadding_LoadPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loadding_LoadPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Loadding_LoadPercent, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loadding_LoadBar = lv_bar_create(ui_Loadding);
    lv_obj_set_height(ui_Loadding_LoadBar, 20);
    lv_obj_set_width(ui_Loadding_LoadBar, lv_pct(100));
    lv_obj_set_x(ui_Loadding_LoadBar, -105);
    lv_obj_set_y(ui_Loadding_LoadBar, 109);
    lv_obj_set_align(ui_Loadding_LoadBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Loadding_LoadBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Loadding_LoadBar,
                                                                                                       lv_obj_get_style_pad_right(ui_Loadding_LoadBar, LV_PART_MAIN) + 1, LV_PART_MAIN);

}
