// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Project

#include "ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Main, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Main_MainTabView = lv_tabview_create(ui_Main);
    lv_tabview_set_tab_bar_size(ui_Main_MainTabView, 50);
    lv_obj_set_width(ui_Main_MainTabView, lv_pct(100));
    lv_obj_set_height(ui_Main_MainTabView, lv_pct(100));
    lv_obj_set_align(ui_Main_MainTabView, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_MainTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Main_Dashboard = lv_tabview_add_tab(ui_Main_MainTabView, "Dashboard");
    lv_obj_set_flex_flow(ui_Main_Dashboard, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_Dashboard, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Dashboard,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Main_DashPanel = lv_obj_create(ui_Main_Dashboard);
    lv_obj_set_width(ui_Main_DashPanel, lv_pct(100));
    lv_obj_set_height(ui_Main_DashPanel, lv_pct(100));
    lv_obj_set_x(ui_Main_DashPanel, -157);
    lv_obj_set_y(ui_Main_DashPanel, -1);
    lv_obj_set_align(ui_Main_DashPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_DashPanel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_Main_DashPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_ZoomBtn = lv_button_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_ZoomBtn, 60);
    lv_obj_set_height(ui_Main_ZoomBtn, 31);
    lv_obj_set_x(ui_Main_ZoomBtn, 185);
    lv_obj_set_y(ui_Main_ZoomBtn, -49);
    lv_obj_set_align(ui_Main_ZoomBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_ZoomBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Main_ZoomBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label9 = lv_label_create(ui_Main_ZoomBtn);
    lv_obj_set_width(ui_Main_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label9, "ZOOM");

    ui_Main_HistoryBtn = lv_button_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_HistoryBtn, 100);
    lv_obj_set_height(ui_Main_HistoryBtn, 35);
    lv_obj_set_x(ui_Main_HistoryBtn, 165);
    lv_obj_set_y(ui_Main_HistoryBtn, -91);
    lv_obj_set_align(ui_Main_HistoryBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_HistoryBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Main_HistoryBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label13 = lv_label_create(ui_Main_HistoryBtn);
    lv_obj_set_width(ui_Main_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label13, "History");

    ui_Main_VolumeArc = lv_arc_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_VolumeArc, 200);
    lv_obj_set_height(ui_Main_VolumeArc, 200);
    lv_obj_set_x(ui_Main_VolumeArc, -2);
    lv_obj_set_y(ui_Main_VolumeArc, 10);
    lv_obj_set_align(ui_Main_VolumeArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_VolumeArc, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_Main_VolumeArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Main_VolumeArc, 0);


    ui_Main_StatusLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_StatusLabel, lv_pct(30));
    lv_obj_set_height(ui_Main_StatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_StatusLabel, -2);
    lv_obj_set_y(ui_Main_StatusLabel, -30);
    lv_obj_set_align(ui_Main_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Main_StatusLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Main_StatusLabel, "Ready");
    lv_obj_set_style_text_color(ui_Main_StatusLabel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Main_StatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_StatusLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_VolumeLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_VolumeLabel, lv_pct(34));
    lv_obj_set_height(ui_Main_VolumeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_VolumeLabel, -2);
    lv_obj_set_y(ui_Main_VolumeLabel, 25);
    lv_obj_set_align(ui_Main_VolumeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_VolumeLabel, "600");
    lv_obj_set_style_text_align(ui_Main_VolumeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_VolumeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_UnitLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_UnitLabel, lv_pct(23));
    lv_obj_set_height(ui_Main_UnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_UnitLabel, -2);
    lv_obj_set_y(ui_Main_UnitLabel, 80);
    lv_obj_set_align(ui_Main_UnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_UnitLabel, "mL");
    lv_obj_set_style_text_align(ui_Main_UnitLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_UnitLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ProgressLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_ProgressLabel, lv_pct(40));
    lv_obj_set_height(ui_Main_ProgressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_ProgressLabel, -130);
    lv_obj_set_y(ui_Main_ProgressLabel, -100);
    lv_obj_set_align(ui_Main_ProgressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_ProgressLabel, "Progress : 0 %");

    ui_Main_TakeTLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_TakeTLabel, lv_pct(32));
    lv_obj_set_height(ui_Main_TakeTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TakeTLabel, -147);
    lv_obj_set_y(ui_Main_TakeTLabel, -75);
    lv_obj_set_align(ui_Main_TakeTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_TakeTLabel, "Take time : 0 s");

    ui_Main_TimeLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_TimeLabel, lv_pct(32));
    lv_obj_set_height(ui_Main_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TimeLabel, -147);
    lv_obj_set_y(ui_Main_TimeLabel, -50);
    lv_obj_set_align(ui_Main_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_TimeLabel, "Time : 0 s");

    ui_Main_DetailLabel = lv_label_create(ui_Main_DashPanel);
    lv_obj_set_width(ui_Main_DetailLabel, lv_pct(30));
    lv_obj_set_height(ui_Main_DetailLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_DetailLabel, 150);
    lv_obj_set_y(ui_Main_DetailLabel, 95);
    lv_obj_set_align(ui_Main_DetailLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_DetailLabel, "Press the \" * + C \" button to cancel.");
    lv_obj_set_style_text_color(ui_Main_DetailLabel, lv_color_hex(0xFF8080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_DetailLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Main_DetailLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_DetailLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Setting = lv_tabview_add_tab(ui_Main_MainTabView, "Setting");
    lv_obj_set_flex_flow(ui_Main_Setting, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_Setting, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Setting, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Main_SettingPanel = lv_obj_create(ui_Main_Setting);
    lv_obj_set_width(ui_Main_SettingPanel, lv_pct(100));
    lv_obj_set_height(ui_Main_SettingPanel, lv_pct(100));
    lv_obj_set_x(ui_Main_SettingPanel, 0);
    lv_obj_set_y(ui_Main_SettingPanel, -1);
    lv_obj_set_align(ui_Main_SettingPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_SettingPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_SettingPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_SettingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_RightContainer = lv_obj_create(ui_Main_SettingPanel);
    lv_obj_remove_style_all(ui_Main_RightContainer);
    lv_obj_set_width(ui_Main_RightContainer, lv_pct(50));
    lv_obj_set_height(ui_Main_RightContainer, lv_pct(100));
    lv_obj_set_align(ui_Main_RightContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_RightContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main_RightContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Main_RightContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_VolContainer = lv_obj_create(ui_Main_RightContainer);
    lv_obj_remove_style_all(ui_Main_VolContainer);
    lv_obj_set_height(ui_Main_VolContainer, 71);
    lv_obj_set_width(ui_Main_VolContainer, lv_pct(100));
    lv_obj_set_x(ui_Main_VolContainer, -24);
    lv_obj_set_y(ui_Main_VolContainer, -70);
    lv_obj_set_align(ui_Main_VolContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_VolContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main_VolContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Main_VolContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Main_VolContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main_VolContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_SVLabel = lv_label_create(ui_Main_VolContainer);
    lv_obj_set_height(ui_Main_SVLabel, 19);
    lv_obj_set_width(ui_Main_SVLabel, lv_pct(100));
    lv_obj_set_x(ui_Main_SVLabel, -41);
    lv_obj_set_y(ui_Main_SVLabel, -16);
    lv_obj_set_align(ui_Main_SVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_SVLabel, "Set Volume");

    ui_Main_SVSpinbox = lv_spinbox_create(ui_Main_VolContainer);
    lv_obj_set_width(ui_Main_SVSpinbox, 70);
    lv_obj_set_height(ui_Main_SVSpinbox, 42);
    lv_obj_set_x(ui_Main_SVSpinbox, -161);
    lv_obj_set_y(ui_Main_SVSpinbox, -72);
    lv_obj_set_align(ui_Main_SVSpinbox, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Main_SVSpinbox, 5, 3);
    lv_spinbox_set_range(ui_Main_SVSpinbox, 10000, 99999);
    lv_spinbox_set_cursor_pos(ui_Main_SVSpinbox, 1 - 1);
    lv_spinbox_set_value(ui_Main_SVSpinbox, 10000);

    ui_Main_SVUnit = lv_dropdown_create(ui_Main_VolContainer);
    lv_dropdown_set_options(ui_Main_SVUnit, "mL\nL");
    lv_obj_set_width(ui_Main_SVUnit, 90);
    lv_obj_set_height(ui_Main_SVUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_SVUnit, -76);
    lv_obj_set_y(ui_Main_SVUnit, -73);
    lv_obj_set_align(ui_Main_SVUnit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_SVUnit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Main_FlowContainer = lv_obj_create(ui_Main_RightContainer);
    lv_obj_remove_style_all(ui_Main_FlowContainer);
    lv_obj_set_height(ui_Main_FlowContainer, 89);
    lv_obj_set_width(ui_Main_FlowContainer, lv_pct(100));
    lv_obj_set_x(ui_Main_FlowContainer, -24);
    lv_obj_set_y(ui_Main_FlowContainer, -70);
    lv_obj_set_align(ui_Main_FlowContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_FlowContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main_FlowContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Main_FlowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Main_FlowContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_FlowContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_FlowContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_FlowContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Main_FlowContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main_FlowContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_SFLabel = lv_label_create(ui_Main_FlowContainer);
    lv_obj_set_height(ui_Main_SFLabel, 19);
    lv_obj_set_width(ui_Main_SFLabel, lv_pct(100));
    lv_obj_set_x(ui_Main_SFLabel, -41);
    lv_obj_set_y(ui_Main_SFLabel, -16);
    lv_obj_set_align(ui_Main_SFLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_SFLabel, "Set Flowrate");

    ui_Main_SFSpinbox = lv_spinbox_create(ui_Main_FlowContainer);
    lv_obj_set_width(ui_Main_SFSpinbox, 70);
    lv_obj_set_height(ui_Main_SFSpinbox, 42);
    lv_obj_set_x(ui_Main_SFSpinbox, -161);
    lv_obj_set_y(ui_Main_SFSpinbox, -72);
    lv_obj_set_align(ui_Main_SFSpinbox, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Main_SFSpinbox, 5, 3);
    lv_spinbox_set_range(ui_Main_SFSpinbox, 10000, 99999);
    lv_spinbox_set_cursor_pos(ui_Main_SFSpinbox, 1 - 1);
    lv_spinbox_set_value(ui_Main_SFSpinbox, 10000);

    ui_Main_SFUnit = lv_dropdown_create(ui_Main_FlowContainer);
    lv_dropdown_set_options(ui_Main_SFUnit, "mL/s\nL/s\nmL/m\nL/m\nL/h");
    lv_obj_set_width(ui_Main_SFUnit, 90);
    lv_obj_set_height(ui_Main_SFUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_SFUnit, -76);
    lv_obj_set_y(ui_Main_SFUnit, -73);
    lv_obj_set_align(ui_Main_SFUnit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_SFUnit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Main_AlarmContainer = lv_obj_create(ui_Main_RightContainer);
    lv_obj_remove_style_all(ui_Main_AlarmContainer);
    lv_obj_set_height(ui_Main_AlarmContainer, 30);
    lv_obj_set_width(ui_Main_AlarmContainer, lv_pct(100));
    lv_obj_set_x(ui_Main_AlarmContainer, -50);
    lv_obj_set_y(ui_Main_AlarmContainer, 55);
    lv_obj_set_align(ui_Main_AlarmContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_AlarmContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_AlarmContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_AlarmContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Main_AlarmContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_AlarmContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_AlarmContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_AlarmContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_WALabel = lv_label_create(ui_Main_AlarmContainer);
    lv_obj_set_width(ui_Main_WALabel, lv_pct(50));
    lv_obj_set_height(ui_Main_WALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_WALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_WALabel, "Water Alarm ");

    ui_Main_WASwitch = lv_switch_create(ui_Main_AlarmContainer);
    lv_obj_set_width(ui_Main_WASwitch, 50);
    lv_obj_set_height(ui_Main_WASwitch, 25);
    lv_obj_add_state(ui_Main_WASwitch, LV_STATE_CHECKED);
    lv_obj_set_align(ui_Main_WASwitch, LV_ALIGN_CENTER);


    ui_Main_LeftContainer = lv_obj_create(ui_Main_SettingPanel);
    lv_obj_remove_style_all(ui_Main_LeftContainer);
    lv_obj_set_width(ui_Main_LeftContainer, lv_pct(50));
    lv_obj_set_height(ui_Main_LeftContainer, lv_pct(100));
    lv_obj_set_x(ui_Main_LeftContainer, 86);
    lv_obj_set_y(ui_Main_LeftContainer, 39);
    lv_obj_set_align(ui_Main_LeftContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_LeftContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main_LeftContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_LeftContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Container2 = lv_obj_create(ui_Main_LeftContainer);
    lv_obj_remove_style_all(ui_Main_Container2);
    lv_obj_set_height(ui_Main_Container2, 54);
    lv_obj_set_width(ui_Main_Container2, lv_pct(90));
    lv_obj_set_x(ui_Main_Container2, -1);
    lv_obj_set_y(ui_Main_Container2, -82);
    lv_obj_set_align(ui_Main_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Main_Container2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Main_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Main_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label8 = lv_label_create(ui_Main_Container2);
    lv_obj_set_width(ui_Main_Label8, lv_pct(75));
    lv_obj_set_height(ui_Main_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label8, "Set Offset");
    lv_obj_set_style_pad_left(ui_Main_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_Label8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Slider1 = lv_slider_create(ui_Main_Container2);
    lv_slider_set_value(ui_Main_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Main_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Main_Slider1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_Slider1, 150);
    lv_obj_set_height(ui_Main_Slider1, 10);
    lv_obj_set_align(ui_Main_Slider1, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Main_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Main_Slider1,
                                                                                                   lv_obj_get_style_pad_right(ui_Main_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Main_SystemContainer = lv_obj_create(ui_Main_LeftContainer);
    lv_obj_remove_style_all(ui_Main_SystemContainer);
    lv_obj_set_height(ui_Main_SystemContainer, 45);
    lv_obj_set_width(ui_Main_SystemContainer, lv_pct(100));
    lv_obj_set_x(ui_Main_SystemContainer, 0);
    lv_obj_set_y(ui_Main_SystemContainer, 75);
    lv_obj_set_align(ui_Main_SystemContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_SystemContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_SystemContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_SystemContainer, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Main_SystemContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Main_SystemContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main_SystemContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ResetBtn = lv_button_create(ui_Main_SystemContainer);
    lv_obj_set_height(ui_Main_ResetBtn, 41);
    lv_obj_set_width(ui_Main_ResetBtn, lv_pct(50));
    lv_obj_set_x(ui_Main_ResetBtn, 114);
    lv_obj_set_y(ui_Main_ResetBtn, 246);
    lv_obj_set_align(ui_Main_ResetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_ResetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Main_ResetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_ResetBtn, lv_color_hex(0xFF3838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_ResetBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ResetLabel = lv_label_create(ui_Main_ResetBtn);
    lv_obj_set_width(ui_Main_ResetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_ResetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_ResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_ResetLabel, "Reset Config");
    lv_obj_set_style_text_color(ui_Main_ResetLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_ResetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_RebootBtn = lv_button_create(ui_Main_SystemContainer);
    lv_obj_set_height(ui_Main_RebootBtn, 41);
    lv_obj_set_width(ui_Main_RebootBtn, lv_pct(40));
    lv_obj_set_x(ui_Main_RebootBtn, 114);
    lv_obj_set_y(ui_Main_RebootBtn, 246);
    lv_obj_set_align(ui_Main_RebootBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_RebootBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Main_RebootBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_RebootBtn, lv_color_hex(0xF96969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_RebootBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_RebootLabel = lv_label_create(ui_Main_RebootBtn);
    lv_obj_set_width(ui_Main_RebootLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_RebootLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_RebootLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_RebootLabel, "Reboot");
    lv_obj_set_style_text_color(ui_Main_RebootLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_RebootLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Info = lv_tabview_add_tab(ui_Main_MainTabView, "Infomation");
    lv_obj_set_flex_flow(ui_Main_Info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_Info, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Info, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Main_InfoPanel = lv_obj_create(ui_Main_Info);
    lv_obj_set_width(ui_Main_InfoPanel, lv_pct(100));
    lv_obj_set_height(ui_Main_InfoPanel, lv_pct(100));
    lv_obj_set_align(ui_Main_InfoPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_InfoPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Main_InfoPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Main_InfoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Main_InfoPanel, &ui_img_btec_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Main_InfoPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_InfoText = lv_label_create(ui_Main_InfoPanel);
    lv_obj_set_width(ui_Main_InfoText, lv_pct(100));
    lv_obj_set_height(ui_Main_InfoText, lv_pct(80));
    lv_obj_set_x(ui_Main_InfoText, -139);
    lv_obj_set_y(ui_Main_InfoText, -80);
    lv_obj_set_align(ui_Main_InfoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_InfoText,
                      "Project Name    :   Liquid Filling Machine\nCreator                 : \n                                    Mr. Kittipop    Manthaisong\n                                    Ms. Sumintra Janklom\nAdvisors               :   \n                                    Mr. Jetsadakorn Salam\n                                    Mr. Kittichanan   Jitkati\n\nDepartment of Electrical Power\nBuriram Technical College");
    lv_obj_set_style_text_color(ui_Main_InfoText, lv_color_hex(0x0007CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_InfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_InfoText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_ZoomBtn, ui_event_Main_ZoomBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_HistoryBtn, ui_event_Main_HistoryBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_WASwitch, ui_event_Main_WASwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_ResetBtn, ui_event_Main_ResetBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_RebootBtn, ui_event_Main_RebootBtn, LV_EVENT_ALL, NULL);

}
